name: build-onyx

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            name: onyx-x86_64
            use_ndk: false
          - target: aarch64-unknown-linux-musl
            name: onyx-aarch64
            use_ndk: false
          - target: aarch64-linux-android
            name: onyx-android-aarch64
            use_ndk: true

    steps:
      - uses: actions/checkout@v4

      - name: install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - name: setup android ndk
        if: ${{ matrix.use_ndk }}
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      # caching cargo-ndk is even more important for nightlies (faster feedback)
      - name: cache cargo-ndk
        if: ${{ matrix.use_ndk }}
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/cargo-ndk
          key: ${{ runner.os }}-cargo-ndk

      - name: install cargo-ndk
        if: ${{ matrix.use_ndk }}
        run: |
          unset CARGO_BUILD_TARGET
          hash cargo-ndk 2>/dev/null || cargo install cargo-ndk --locked

      - name: build optimized binary
        run: |
          if [ "${{ matrix.use_ndk }}" = "true" ]; then
            cargo ndk -t aarch64-linux-android build --release
            cp target/aarch64-linux-android/release/onyx ./${{ matrix.name }}
          else
            cargo build --release --target ${{ matrix.target }}
            cp target/${{ matrix.target }}/release/onyx ./${{ matrix.name }}
          fi

      - name: strip symbols
        run: strip ${{ matrix.name }} || echo "strip failed, continuing..."

      - name: upload brute binaries
        uses: actions/upload-artifact@v4
        with:
          # artifact names must be unique per matrix job
          name: ${{ matrix.name }}-artifact
          path: ${{ matrix.name }}
          retention-days: 5