name: release-onyx
on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            suffix: x86_64
          - target: aarch64-unknown-linux-musl
            suffix: aarch64
    steps:
      - uses: actions/checkout@v4
      - name: install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools upx-ucl gcc-aarch64-linux-gnu
      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: build release
        run: |
          # tell cargo to use the right linker for arm64
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc
          cargo build --release --target ${{ matrix.target }}
      - name: compress & rename
        run: |
          upx --brute ./target/${{ matrix.target }}/release/onyx
          mv ./target/${{ matrix.target }}/release/onyx ./onyx-${{ matrix.suffix }}
      - name: upload release
        uses: softprops/action-gh-release@v2
        with:
          files: onyx-${{ matrix.suffix }}